### ISSUE TITLE
Turn this into an allow-list

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-unsafe-expose-env#1]
Then I can rename it to `datasette-expose-env` because it will be safe by default.

**Comment by jefftriplett** [comment]
Is the goal really to be unsafe or are you open to using something like Django's ` hidden_settings` to hide some common patterns? 

https://github.com/django/django/blob/0dd29209091280ccf34e07c9468746c396b7778e/django/views/debug.py#L112-L114

**Comment by simonw** [comment]
I just came across the need to hide `SENTRY_DSN` which wouldn't have been caught by that regex. I think I'm going to go full circle and turn it into an allow-list - I really prefer things like this to be safe by default.

**Comment by simonw** [comment]
I'm actually going to leave this plugin here, put it in archive mode and build a new `datasette-expose-env` plugin in a separate repo.

**Comment by simonw** [comment]
That plugin is now released:
- https://pypi.org/project/datasette-expose-env/
- https://github.com/simonw/datasette-expose-env
- https://datasette.io/plugins/datasette-expose-env
